#!/usr/bin/env bash
# shellcheck disable=SC2034
# SPDX-License-Identifier: MIT
# Copyright (C) 2023 Utsav Balar
# Copyright (C) 2023 Vicharak Computers LLP

# Date for boot image
DATE=$(date +"%d.%m.%y")
export DATE

# Kernel directory path
export KERNEL_DIR="${SCRIPT_DIR}"/..

# Kernel out directory path
export OUT_DIR=${KERNEL_DIR}/out

# Set boot image name
export FILENAME="${OUT_DIR}/boot-${DATE}.img"

# Set default extlinux config
export EXTLINUX_CONF="${KERNEL_DIR}/extlinux/vicharak.conf"

# Get kernel version
function get_kernel_version() {
	if [ -f "${OUT_DIR}"/include/config/kernel.release ]; then
		KERNEL_VERSION=$(cat "${OUT_DIR}"/include/config/kernel.release 2>/dev/null)
	else
		local version patchlevel sublevel
		version=$(grep -w "VERSION =" "${SCRIPT_DIR}"/../Makefile | awk '{print $3}')
		patchlevel=$(grep -w "PATCHLEVEL =" "${SCRIPT_DIR}"/../Makefile | awk '{print $3}')
		sublevel=$(grep -w "SUBLEVEL =" "${SCRIPT_DIR}"/../Makefile | awk '{print $3}')

		KERNEL_VERSION="${version}.${patchlevel}.${sublevel}"
	fi

	echo "${KERNEL_VERSION}"
}

# Kernel version
KERNEL_VERSION=$(get_kernel_version)
export KERNEL_VERSION

# Default Clang toolchain directory
export CLANG_DIR=${KERNEL_DIR}/../clang

# Default Clang version
export DEFAULT_CLANG_VERSION=12

# Default GCC toolchain directory
export GCC64_DIR=${KERNEL_DIR}/../gcc-"${DEVICE_ARCH}"
export GCC32_DIR=${KERNEL_DIR}/../gcc32

# set PS3 prompt
export PS3="Select device: "

# Host system
HOST_SYSTEM=$(grep "^ID=" /etc/os-release | cut -d'=' -f2)
export HOST_SYSTEM
